name: flutter_i18n
description: i18n made easy for Flutter. With flutter_i18n you can make your app international, using just a simple .json file!
version: 0.32.4
homepage: https://github.com/ilteoood/flutter_i18n
issue_tracker: https://github.com/ilteoood/flutter_i18n/issues

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.17.0
  yaml: ^3.1.0
  xml2json: ^5.3.2
  path: ^1.8.0
  toml: ^0.13.1
  logging: ^1.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

environment:
  sdk: '>=2.12.0 <3.0.0'
