name: flutter_i18n
description: i18n made easy for Flutter. With flutter_i18n you can make your app international, using just a simple .json, .xml, .yaml or .toml file!
version: 0.36.3
homepage: https://github.com/ilteoood/flutter_i18n
issue_tracker: https://github.com/ilteoood/flutter_i18n/issues

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ">=0.17.0-0 <1.0.0"
  yaml: ^3.1.3
  xml2json: ^6.2.7
  path: ^1.9.1
  toml: ^0.16.0
  logging: ^1.3.0
  http: ^1.4.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

environment:
  sdk: ">=2.12.0 <4.0.0"
