name: flutter_i18n
description: i18n made easy for Flutter. With flutter_i18n you can make your app international, using just a simple .json file!
version: 0.21.0
homepage: https://github.com/ilteoood/flutter_i18n

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.16.0
  yaml: ^2.2.0
  xml2json: ^4.2.0
  merge_map: ^1.0.2
  universal_io: ^1.0.1
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

environment:
  sdk: '>=2.3.0 <3.0.0'
